### ISSUE TITLE
Volume resets every time a new track starts [Expires May 22, 2018]

### ISSUE THREAD

**Issue by dannosaur** [tiliado/nuvola-app-plex#6] opened 2016-08-08 07:17 UTC
Which can be quite startling if you have headphones in :)

I can turn the volume up/down with the system controls, but whenever a new track starts, it resets the volumn back to what it was previously (which can be loud!)

**Comment by skyghis** [comment] 2016-08-08 10:02
Hi,

Thanks for reporting this issue.
Could you please provide your basic system informations ?
https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines

The reseting volume is the Plex yellow volume bar or the system volume ?
The issue occur only with headphones ?

**Comment by dannosaur** [comment] 2016-08-08 11:25
Fedora 23 x64, GNOME 3.18.5
Nuvola Player 3.0.3 8e3fd1301c4f05512806 (installed via Tiliado RPM repo)

It doesn't appear to matter whether headphones are in or not (more noticeable if they are). When a track changes, the yellow bar in Plex resets to almost 100%, and that in turn sets PulseAudio's volume control to the same level. In fact, every time a new track starts, it increases. Even if I *don't* decrease the volume manually and skip to another track, it sets the volume higher than it did for the last track. This continues until it hits 100%.

I enabled debug mode, but looking through it there doesn't appear to be anything relating to the setting of the system volume. When I increase/decrease the volume controls, either from within Plex or using the system controls, no output is observed. If you want me to attach a debug output anyway, let me know and I'll provide.

**Comment by fenryxo** [comment] 2016-08-08 17:25
Hello @dannosaur. The WebKitGTK+ library (the web rendering engine used by Nuvola Player) has currently unresolved issues regarding PulseAudio and volume handling. The best workaround is to disable flat-volumes in the PulseAudio configuration.

> When a track changes, the yellow bar in Plex resets to almost 100%, and that in turn sets PulseAudio's volume control to the same level. In fact, every time a new track starts, it increases. Even if I don't decrease the volume manually and skip to another track, it sets the volume higher than it did for the last track. This continues until it hits 100%.

Well, it looks like a bug in Plex itself. Once the volume in the in-app volume bar is set, it shouldn't increase on its own.

**Comment by dannosaur** [comment] 2016-08-08 17:31
> Well, it looks like a bug in Plex itself. Once the volume in the in-app volume bar is set, it shouldn't increase on its own.

I thought this too, so I went over to the Plex web UI directly in Chrome and it behaved normally (not increasing the volume as tracks passed by). Granted the browser doesn't expose much of the system's volume controls to anything running inside it, so this might have had something to do with it, and if WebKitGTK+ has issues with this currently, then that's probably exacerbating the situation.

It's strange it doesn't do this with Google Play Music though - just Plex (I can't test the other integrations, I don't have accounts on any of them).

**Comment by skyghis** [comment] 2016-08-11 17:44
I currently don't have a reliable Internet access. I'll try to reproduce this issue in a few week.

**Comment by skyghis** [comment] 2016-08-19 13:41
I tested and I can reproduce the bug (v3.0.3; WebKitGTK 2.10.9).
This don't seem to be a Plex issue because the issue can't be reproduced on Firefox and Chromium.

> The WebKitGTK+ library (the web rendering engine used by Nuvola Player) has currently unresolved issues regarding PulseAudio and volume handling. The best workaround is to disable flat-volumes in the PulseAudio configuration.

I will try to test pulseaudio settings this week-end.

**Comment by skyghis** [comment] 2016-08-29 08:52
Ubuntu seem to disable pulseaudio flat volumes by default.
```
$cat /etc/pulse/daemon.conf | grep flat
flat-volumes = no
```
I observe  a different behaviour between Chromium and Nuvolaplayer:

Nuvolaplayer seem to detach and reattach the sound process (The process is always the same) and the sound volume is changed on pulseaudio when changing the Plex volume bar 
![nuvola](https://cloud.githubusercontent.com/assets/1068552/18045784/db2f4f58-6dd4-11e6-863c-3a3b9b9d5725.gif)


Chromium seem to attach sound process only once and don't bind volume bar.
![chromium](https://cloud.githubusercontent.com/assets/1068552/18045898/7927bce0-6dd5-11e6-9e4b-430515766326.gif)

Unfortunately I have no idea on how to *fix* that.

I could try to force the Plex volume bar position on the integration script between each song, but this sound like a bad idea.

Tested under Ubuntu 16.04; Nuvola v3.0.3; WebKitGTK 2.10.9; Chromium 51.0.2704.79

**Comment by fenryxo** [comment] 2016-08-29 11:04
The key is to understand why the volume jumps up on song change. Is the jump always same? Are there any audio elements  found by `document.getElementsByTagName("audio");`?

**Comment by skyghis** [comment] 2016-08-31 16:40
`document.getElementsByTagName("audio");` Return a single audio element.

For information the volume increase at each song change (prev or next).
For example : 13% -> 51% -> 80% -> 93% -> 98% -> 99% -> 100%
The volume is stuck to 100% after

I try to add find in the JavaScript (via breakpoint)  the  source of the volume change.

**Comment by fenryxo** [comment] 2016-08-31 16:57
> I try to add find in the JavaScript (via breakpoint) the source of the volume change.

:+1:

**Comment by skyghis** [comment] 2016-09-12 13:47
No hit for the source of the signal who trigger volume increase.
I got the same behaviour when using the WebKitGtk MiniBrowser.

When searching for information, I find this issue: https://github.com/tiliado/nuvola-app-google-play-music/issues/11. Could be related ?

**Comment by fenryxo** [comment] 2018-04-22 18:10
Hello @dannosaur. Is the issue reproducible with Plex server 1.12.2 with Nuvola 4.10.29 & Plex script 1.3.6?

**Comment by fenryxo** [comment] 2018-05-29 09:32
Closing as expired because there has not been any response for a month. Feel free to add requested information to reopen this issue.

**Closed by fenryxo** 2018-05-29 09:32 UTC
Labels: need info
