### ISSUE TITLE
Problems to connect

### ISSUE THREAD

**Issue by Saxfusion** [tiliado/nuvola-app-plex#5] opened 2015-12-14 22:14 UTC
I am running the plex server 0.9.14.4 on a Synology NAS (DSM 5.2 latest).
The user-webserver of the NAS is running on ssl and hsts (might be where the problems come from)
plex server is also equipped with a custom SSL cert.

In the nuvola plex setting i have configured
https://url:32400/web  (which is working fine within a "normal" browser)
I end up getting displayed the plex logo only.
If i use plain http i get a blank screen with "Message corrupt"

Any hints for a structured trouble-shoot?

**Comment by skyghis** [comment] 2015-12-15 12:40
You run Nuvolaplayer on which OS / version ?

**Comment by Saxfusion** [comment] 2015-12-17 19:13
Host OS for the player is Ubuntu 15.10

**Comment by skyghis** [comment] 2015-12-17 19:35
I reproduce the bug with Ubuntu 15.10, even without https / ssl / hsts
Looks like the javascript file `plex.js` can't be loaded. It's totally over my knowledge and will require some help from @fenryxo

**Comment by fenryxo** [comment] 2015-12-22 14:22
Hello. Could anyone post a debugging output as specified in [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines)? It might contain some information.

**Comment by skyghis** [comment] 2015-12-22 19:37
Ubuntu 15.10 x86_64
Nuvola Player 3 Beta 3.0.0+201512221156.7eac479
Output log : https://gist.github.com/skyghis/1aeec5e29c7fea4e1a53 (I replaced my personal host name by dash)
I get the same behaviour using `webkit2gtk-4.0/MiniBrowser`

No problem using Chromium or Firefox.

**Comment by fenryxo** [comment] 2015-12-23 06:24
Thanks. Now it is necessary to get the code of "http://-------.-------.---:32400/web/js/plex.js?hash=f1c2b98&version=2.4.23:832" and find the cause of the error at line 287: `TypeError: null is not an object (evaluating 'this.cache.getItemCacheKey')`.

**Comment by fenryxo** [comment] 2015-12-23 06:28
> Now it is necessary to get the code of...

Right click anywhere→ Inspect element → Resources → Scripts → plex.js.

**Comment by skyghis** [comment] 2015-12-23 07:54
I send you my host name by mail to ease your tests.

**Comment by fenryxo** [comment] 2015-12-23 10:07
> I send you my host name by mail to ease your tests.

Actually, I would prefer you to investigate this issue further as you are the maintainer of this integration. I can guide you a bit though.

**Comment by brambo23** [comment] 2016-01-05 19:25
I came across the same problem as well.  It seems to happen when you require HTTPS to be used on your server end.  I changed the Server Settings (Show Advanced) - Network - Secure Connections -  I changed it from Required to Preferred and the Page showed right up.  I tried adding https into the URL of the server in the Preferences of the player but it seemed to still try and load it over HTTP.

Hope this helps

**Comment by Dark-Planet** [comment] 2016-02-25 23:07
To fix the problem on Ubuntu 15.10 (Wily Werewolf) 64-bit, you must update package libwebkit2gtk to version (2.10.6-1) It seems that this is not a problem of nuvola-app-plex but rather outdated WebKit

**Comment by skyghis** [comment] 2016-03-07 08:29
Sorry for the delayed answer, some personal issues.

After multiples tries, I can't debug the content of the javascript, the UI freeze when I tries to debug.

It seem that I have `libwebkit2gtk-3.0-25` currently installed.  @Dark-Planet can you explain me how to replace it with version `2.10.6-1` to test ?

**Comment by Dark-Planet** [comment] 2016-03-07 17:09
In order to update, add the repository webkit-team

sudo add-apt-repository ppa:webkit-team
sudo apt-get update

then delete the old libwebkit2gtk-4.0-37 2.8.5+dfsg1-3 by command

sudo apt-get remove libwebkit2gtk-4.0-37

and then reinstall again

sudo apt-get install libwebkit2gtk-4.0-37 nuvolaplayer3

after this operation, you should have the latest version of webkit (2.10.6)

libwebkit2gtk-4.0-37 2.10.6-1~15.10~webkitteam1

I might add that a simple update does not work.

**Comment by skyghis** [comment] 2016-03-07 17:31
Thanks @Dark-Planet !

On my machine less steps work great:
```
sudo add-apt-repository ppa:webkit-team
sudo apt-get update
sudo apt-get dist-update
sudo apt-get autoremove
sudo apt-get autoclean
``` 
Run NuvolaPlayer Plex just after and it works again :+1:

**Comment by fenryxo** [comment] 2016-03-10 14:49
Hello @skyghis. Could you create [a wiki page Known Issues](https://github.com/tiliado/nuvola-app-plex/wiki) similar to [the Known Issues of Google Play Music script](https://github.com/tiliado/nuvola-app-google-play-music/wiki/Known-Issues), add this issue to the page and the procedure describing how to update WebKitGTK library? Then you can close this ticket. Thanks!

**Comment by skyghis** [comment] 2016-03-12 12:00
Fix procedure tested on an other computer added to wiki page [Known Issues](https://github.com/tiliado/nuvola-app-plex/wiki/Known-Issues#plex-loading-screen-freeze)

**Closed by skyghis** 2016-03-12 12:00 UTC
Labels: bug, help wanted
